### ISSUE TITLE
Assign ID's to Pi's that are transmitted querying. Can detecting dead Pi's.

### ISSUE THREAD

**Issue by spac3lord** [TweakMunich/metricsinyourface#15]

**Comment by mdan1eli** [comment]
This is linked with #20.

Pi´s have an ID, their serial we can read in Python, I used it for registering on Mongo the sensor data

We could also update life-cycle so we register POST upon program start-up and deregister upon graceful shutdown.  This would let me detect which Pi´s exist and which should be alive.  I can move offline if they miss the heartbeat (which I measure with a filter on the server).  Could work?

**Comment by spac3lord** [comment]
http://stackoverflow.com/questions/4271740/how-can-i-use-python-to-get-the-system-hostname

http://www.raspberrypi-spy.co.uk/2012/09/getting-your-raspberry-pi-serial-number-using-python/

I think just a heartbeat is good for start. Graceful shutdown will let you determien whether it was intentionally taken off-line or died. Catch is the current code has no graceful shutdown :-o

**Comment by mdan1eli** [comment]
server side is expecting a header.  current iplementation uses hostname header, but could switch to different value.
