### ISSUE TITLE
Add a management console 

### ISSUE THREAD

**Issue by spac3lord** [TweakMunich/metricsinyourface#20]
Shows which Pi's have queries what parameters when, so we can detect 'dead' Pi's

**Comment by mdan1eli** [comment]
I will look into this as soon. Would integration with cloudwatch be considered viable or should we consider a on pemise solution?

**Comment by spac3lord** [comment]
This runs in cloud anyway, so that's no issue.

We should separate monitoring of the Pi's from monitoring the site

**Comment by mdan1eli** [comment]
Implemented monitoring of metric request, by adding a special domain _system_ and using dedicated channels with ID = 1 and ID = 2.  The display can monitor the status.
